apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oxr0x3dp6-nodejs
  janus-idp.io/tekton: oxr0x3dp6-nodejs
  backstage.io/kubernetes-id: oxr0x3dp6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oxr0x3dp6-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
