apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oxr0x3dp6-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oxr0x3dp6-nodejs 
  name: oxr0x3dp6-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oxr0x3dp6-nodejs 
